# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LaTeX-Kurs
longtitle: LaTeX Kurs WS 2018
email: support@latexkurs.de
description: Einführung in das Textsatzsystem LaTeX im WS 2018 an der Uni Heidelberg
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://latexkurs.github.io" # the base hostname & protocol for your site
twitter_username: imntl_
github_username:  imntl

# Build settings
markdown: kramdown
